modLoader="javafml" #mandatory
loaderVersion="[25,)"
issueTrackerURL="https://github.com/alwyn974/DRP/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="discordrichpresence" #mandatory
version="1.0.0" #mandatory
displayName="Discord Rich Presence Mod" #mandatory
updateJSONURL="https://alwyn974.github.io/mods/updates/drp_update.json" #optional
displayURL="https://github.com/alwyn974/DRP" #optional
logoFile="" #optional
credits="Credit to Alwyn974" #optional
authors="Alwyn974" #optional
description='''
Discord Rich Presence Mod !
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.discordrichpresence]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.discordrichpresence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,)"
    ordering="NONE"
    side="BOTH"